mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('time_manager/', include('time_manager.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index'),
    path('<int:pk>/', views.DetailView.as_view(), name = 'detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name = 'results'),
    path('<int:question_id>/vote/', views.vote, name = 'vote'),
]

time_manager/urls.py
from django.urls import path
from . import views

app_name = 'time_manager'
urlpatterns = [
    path('', views.IndexView, name = 'index'),
    path('signup/', views.signup_view, name = 'signup'),
    path('signin/', views.signin_view, name = 'signin'),
    path('logout/', views.logout_view, name = 'logout'),
    path('<slug:username>/', views.AccountView, name = 'account'),
    path('<slug:username>/task_<int:task_id>_change/', views.task_changeView, name = 'task_change'),
    path('<slug:username>/create_task/', views.task_createView, name = 'task_create'),
]

time_manager/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.exceptions import ValidationError


class Task(models.Model):
    user = models.ForeignKey(User, null = True, blank = True, on_delete = models.CASCADE)
    task_text = models.CharField(max_length = 200)
    task_start_date = models.DateTimeField('date start')
    def create_task(self, task_text, task_start_date):
        book = self.create(task_text = task_text, task_start_date = task_start_date)
        return book

    def __str__(self):
        return self.task_text

    def start_soon(self):
        now = timezone.now()
        return datetime.timedelta(days = 0) <= self.task_start_date - now <= datetime.timedelta(days = 1)


class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label = 'Enter username', min_length = 4, max_length = 150,
                widget = forms.TextInput(attrs={'placeholder': 'Username',
                                                'class' : 'form-control'}))
    email = forms.EmailField(label = 'Enter email',
                widget = forms.TextInput(attrs={'placeholder': 'Email',
                                                'class' : 'form-control',
                                                'type' : 'email'}))
    password1 = forms.CharField(label = 'Enter password',
                widget = forms.TextInput(attrs={'placeholder': 'Password',
                                                'class' : 'form-control',
                                                'type' : "password"}))
    password2 = forms.CharField(label = 'Confirm password',
                widget = forms.TextInput(attrs={'placeholder': 'Confirm password',
                                                'class' : 'form-control',
                                                'type' : "password"}))

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username = username)
        if r.count():
            raise ValidationError("Username already in use!")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email = email)
        if r.count():
            raise ValidationError("Email already in use!")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise ValidationError("Password doesn't match!")
        return password2

    def save(self, commit = True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user;

class TaskCreationForm(forms.Form):
    task_text = forms.CharField(label = 'Enter text of the task', min_length = 4, max_length = 150,
                                widget = forms.TextInput(attrs={'placeholder': 'Task text',
                                                                'class' : 'form-control'}))
    task_date = forms.DateTimeField(widget = forms.TextInput(attrs={'placeholder': 'YYYY-MM-DD HH:MM'}))

    def clean_task_text(self):
        task_text = self.cleaned_data['task_text'].lower()
        return task_text

    def clean_task_date(self):
        task_date = self.cleaned_data['task_date']
        return task_date

    def save(self, username, commit = True):
        task = Task(
            user = User.objects.get(username = username),
            task_text = self.cleaned_data['task_text'],
            task_start_date = self.cleaned_data['task_date']
        )
        task.save()

time_manager/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from .models import CustomUserCreationForm, TaskCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.utils.dateparse import parse_datetime
from django.core.mail import send_mail
from django.conf import settings

import sched, time

from datetime import datetime
from .models import Task

from django.contrib.auth import authenticate
# Create your views here.

"""
sheduler = sched.scheduler(time.time, time.sleep)

def emailSender(sc):
    for task in Task.objects.all():
        if task.start_soon():
            send_mail(
                'There is notification from time manager',
                'Your task: ' + task.task_text + ' will start in one day!',
                settings.EMAIL_HOST_USER,
                Task.user.email
            )
            sheduler.enter(600, 1, emailSender, (sc,))

sheduler.enter(600, 1, emailSender, (sheduler,))
sheduler.run()
"""

def IndexView(request):
    template_name = 'time_manager/index.html'
    return render(request, template_name)

def task_changeView(request, username, task_id):
    if not request.user.is_authenticated or not request.user.username == username:
        return render(request, 'time_manager/index.html', {'error_message' : 'not logged in'})
    else:
        task = get_object_or_404(Task, pk = task_id)
        if task.user.username == username:
            if request.method == 'POST':
                if not request.POST.get('deleteTask'):
                    task.task_text = request.POST.get('newTaskText')
                    task.task_start_date = parse_datetime(request.POST.get('newTaskDate'))#, '%Y-%m-%d %H:%M')
                    task.save()
                else:
                    task.delete()
                #return render(request, 'time_manager/account.html')
                return HttpResponseRedirect(reverse('time_manager:account', args = (username,)))
            else:
                return render(request, 'time_manager/task_change.html', {'user' : request.user, 'task' : task})
        else:
            return render(request, 'time_manager/index.html', {'error_message' : 'its not your task'})


def task_createView(request, username):
    if not request.user.is_authenticated or not request.user.username == username:
        return render(request, 'time_manager/index.html', {'error_message' : 'not logged in'})
    else:
        if request.method == 'POST':
            form = TaskCreationForm(request.POST)
            if form.is_valid():
                form.save(username)
                return render(request, 'time_manager/account.html')
        else:
            form = TaskCreationForm()
            return render(request, 'time_manager/task_create.html', {'user' : request.user, 'form' : form})

def AccountView(request, username):
    template_name = 'time_manager/account.html'
    if not request.user.is_authenticated or not request.user.username == username:
        return render(request, 'time_manager/index.html', {'error_message' : 'not logged in'})
    else:
        return render(request, template_name)


def signup_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('time_manager:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'time_manager/signup.html', {'form' : form})


def signin_view(request):
    if request.method == 'POST':
        user = authenticate(username = request.POST.get('username'),
                            password = request.POST.get('password'))
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('time_manager:account', args = (request.POST['username'],)),
                                        {'user' : user})
        else:
            return render(request, 'time_manager/index.html',
                          {'error_message' : "No user or bad pass!"})

def logout_view(request):
    logout(request)
    return render(request, 'time_manager/index.html',
                  {'error_message' : "Succesfull logout"})

time_manager/templates/time_manager/account.html
<h1> There is list of your tasks, dear {{ user.username }} </h1>
{% if not user.task_set.count == 0 %}
  <ul>
  {% for task in user.task_set.all %}
    <li> "{{ task.task_text }}" starts {{ task.task_start_date }}
      <a href = "{% url 'time_manager:task_change' user.username task.id %}"> change/del </a> </li>
  {% endfor %}
  </ul>
  <a href = "{% url 'time_manager:task_create' user.username %}">Create new task</a>
  <BR>
{% else %}
  There aren't any tasks!
  <BR>
  Whould you like to create one? <a href = "{% url 'time_manager:task_create' user.username %}"> YES!</a>
  <BR>
{% endif %}
<a href = "{% url 'time_manager:logout' %}"> LOGOUT </a>

time_manager/templates/time_manager/index.html
{% load static %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'time_manager\css\bootstrap.css' %}" crossorigin="anonymous">
  </head>
    <body class="text-center" style="">
      <form class="form-signin" action = "{% url 'time_manager:signin' %}" method = "post">
        {% csrf_token %}
        <h1 class="h3 mb-3 p-5 font-weight-normal">Please sign in</h1>
        <div class = "w-25 mx-auto">
          <label class="sr-only">Username</label>
          <input type="text" name = "username" class="form-control" placeholder="Username" required="" autofocus="">
          <label class="sr-only">Password</label>
          <input type="password" name = "password" class="form-control" placeholder="Password" required="">
        </div>
        <!--<div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>-->
        <div class = "w-25 mx-auto">
          <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </div> <BR>
        <a href = "{% url 'time_manager:signup' %}"  class="btn btn-primary btn-lg active" role="button" aria-pressed="true">HAVEN'T REGESTERED YET?</a>
      </form>
  </body>
</html>

time_manager/templates/time_manager/signup.html
{% load static %}
{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'time_manager\css\bootstrap.css' %}" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'time_manager\style.css' %}">
  </head>
    <body class="text-center" style="">
      <form class="form-signin" method = "post">
        {% csrf_token %}
        <h1 class="h3 mb-3 p-5 font-weight-normal">Please fill all lines</h1>
        <div class = "w-25 mx-auto">
          {{ form.username }}
          {% if form.errors.username %}
            <footer class="blockquote-footer">
                {{form.errors.username.as_text}}
            </footer>
          {% endif %}
          {{ form.email }}
          {% if form.errors.email %}
            <footer class="blockquote-footer">
                {{form.errors.email.as_text}}
            </footer>
          {% endif %}
          {{ form.password1 }}
          {{ form.password2 }}
          {% if form.errors.password2 %}
            <footer class="blockquote-footer">
                {{form.errors.password2.as_text}}
            </footer>
          {% endif %}
        </div> <BR>
        <div class = "w-25 mx-auto">
          <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
        </div> <BR>
      </form>
  </body>
</html>

{% endblock %}

time_manager/templates/time_manager/task_change.html
{% load static %}
{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'time_manager\css\bootstrap.css' %}" crossorigin="anonymous">
  </head>
<body class="text-center" style="">
  <form action = "{% url 'time_manager:task_change' user.username task.id %}" method = "post">
    {% csrf_token %}
    <h1 class="h3 mb-3 p-5 font-weight-normal">Please fill all lines</h1>
    <div class = "w-25 mx-auto">
      <input maxlength="150" minlength="4" required = "" type = "text" value = "{{ task.task_text }}" name = "newTaskText">
      <br>
      <input type = "datetime" value = "{{ task.task_start_date|date:'Y-m-d H:i'}}" name = "newTaskDate">
      <br> Delete :
      <input type = "checkbox" name = "deleteTask">
    <div class = "w-25 mx-auto">
      <button class="btn btn-lg btn-primary btn-block" type="submit">Change</button>
    </div> <BR>
  </form>
</body>
</html>

{% endblock %}

time_manager/templates/time_manager/task_create.html
{% load static %}
{% block content %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'time_manager\css\bootstrap.css' %}" crossorigin="anonymous">
  </head>
<body class="text-center" style="">
  <form action = "{% url 'time_manager:task_create' user.username %}" method = "post">
    {% csrf_token %}
    <h1 class="h3 mb-3 p-5 font-weight-normal">Please fill all lines</h1>
    <div class = "w-25 mx-auto">
      {{ form.task_text }}
      {% if form.errors.task_text %}
        <footer class="blockquote-footer">
            {{form.errors.task_text.as_text}}
        </footer>
      <br>
      {% endif %}
      {{ form.task_date }}
      {% if form.errors.task_date %}
        <footer class="blockquote-footer">
            {{form.errors.task_date.as_text}}
        </footer>
      {% endif %}
    <div class = "w-25 mx-auto">
      <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
    </div> <BR>
  </form>
</body>
</html>

{% endblock %}